### ISSUE TITLE
网页版本客户端本地运行不起来

### ISSUE THREAD

**Issue by songxuexian** [liangdas/mqant#1]
你好，我是一个GO新手，我想问下，按照你的教程，启动网页版本客户端，但是到了登陆界面点击join网页转不到对话页面，能不能给点指导呢，thanks.
下面是运行的截图
![image](https://cloud.githubusercontent.com/assets/12974811/23498232/99f1ead6-ff61-11e6-88d5-b10a7408cd16.png)

![image](https://cloud.githubusercontent.com/assets/12974811/23498314/2abe8dc6-ff62-11e6-8dc5-8bc8408ace2f.png)

**Comment by liangdas** [comment]
你好，请加群讨论吧 463735103

**Comment by songxuexian** [comment]
已经可以运行。
