### ISSUE TITLE
是否handler处理返回只支持返回 int64呢？此方法只判断了int64

### ISSUE THREAD

**Issue by sun-wenming** [liangdas/mqant#100]
https://github.com/liangdas/mqant/blob/0038ce3a83b0920831aac290b681f62200a4435f/rpc/reply.go#L27

**Comment by liangdas** [comment]
rpc通信支持数据格式有这些 http://docs.mqant.com/rpc_data_structure.html
不过返回内容你需要自己断言判断类型

**Comment by sun-wenming** [comment]
好的
