### ISSUE TITLE
能否出一些数据库操作相关的例子

### ISSUE THREAD

**Issue by linarykiss** [liangdas/mqant#103]
你好，我是一个golang初学者，最近在看您的mqant框架，看完文档后想实操一下，发现缺少数据库使用相关的例子。
由于我自己也是刚刚接触go语言，不太了解在您的框架里该如何使用数据库（mongo，mysql等），是加一个数据库module，通过消息传递的方式，或者直接使用第三方数据库包通过groutine去读写数据库？
希望大大能出一些例子或者给一些方向性的指导，万分感谢！

**Comment by liangdas** [comment]
我可以做一些mongo操作的例子，最近在整理写文章，到时请关注

**Comment by linarykiss** [comment]
good~
