### ISSUE TITLE
老哥还在维护吗？

### ISSUE THREAD

**Issue by AnkoGo123** [liangdas/mqant#114]
我想用这个框架，希望有问题的话可以得到老哥的及时帮助。期待回复~

**Comment by AnkoGo123** [comment]
你的框架写的非常出色，只是go mod没有，我在想怎么升级到go mod版本，期待后期一起维护

**Comment by AnkoGo123** [comment]
相见恨晚

**Comment by liangdas** [comment]
还在维护哈，我也一直在用，gomod老早就已经支持了

**Comment by liangdas** [comment]
欢迎加入一起来维护

**Comment by AnkoGo123** [comment]
想问下支持websocket通信吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月1日(周一) 上午9:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liangdas/mqant] 老哥还在维护吗？ (Issue #114)




 
还在维护哈，我也一直在用，gomod老早就已经支持了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
