### ISSUE TITLE
支持websocket通信吗？

### ISSUE THREAD

**Issue by AnkoGo123** [liangdas/mqant#115]
支持与前端进行websocket通信吗？

**Comment by AnkoGo123** [comment]
老哥在吗？回复下

**Comment by liangdas** [comment]
支持，你有看你的上次提的问题吗？

**Comment by liangdas** [comment]
mqtt库有websocket版本，只要找到mqtt js库就行，我用mqtt开发过小游戏，小程序，cocos creator的游戏都可以

**Comment by AnkoGo123** [comment]
看了，我确实要用来做cocos creator，所以他只支持websocket，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月3日(周三) 中午11:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liangdas/mqant] 支持websocket通信吗？ (Issue #115)




 
支持，你有看你的上次提的问题吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
