### ISSUE TITLE
go1.17支持吗

### ISSUE THREAD

**Issue by AnkoGo123** [liangdas/mqant#117]
go1.17支持吗？我还在徘徊用不用你的框架，学习成本会不会很大？无奈啊，我要开发整个游戏，聊天系统（私人，好友，世界），登录系统，游戏系统，我就发觉必须拆开服务，不然写到后期我我头发都乱，期望得到贵hub主的贴心回复与指导

**Comment by AnkoGo123** [comment]
http://www.mqant.com/topic/5a4b80dd059371587f944007
这个帖子上面的问题解决了吗？目前想用这个库https://github.com/liangdas/MQTT.js/blob/master/umdMqtt.js，但是看评论说android,ios，微信小程序，web并不是所有端都可以正常通信，请问4年过去了，上面的umdMqtt.js在cocos creator2.4.6中使用是否可以正常通信？请楼主帮忙测试下android,ios和微信小程序，非常感谢，希望楼主及时回复

**Comment by liangdas** [comment]
我没有用go1.17编译过，按道理应该是向下兼容多
cocos creator 可以参考这个库
https://github.com/liangdas/mqant-cocoscreate

**Comment by zjz91010** [comment]
请问用上go1,17，go1.19了吗？？？
分享一下示例docker
谢谢
