### ISSUE TITLE
http://127.0.0.1:8090/httpgate/topic

### ISSUE THREAD

**Issue by jerrylu2011** [liangdas/mqant#119]
根据文档，在练习mqant-example测试到http://127.0.0.1:8090/httpgate/topic的时候报错了，新手还不是很明白。
OS：MacOS 11.6.2 X86
Go version：1.17.6 
Exception has occurred: runtime error
invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation]
Unable to propagate EXC_BAD_ACCESS signal to target process and panic (see https://github.com/go-delve/delve/issues/852)
Stack:
	0  0x00000000016e971b in github.com/liangdas/mqant/rpc/base.(*RPCServer)._runFunc
	    at /Users/jerrylu/go/pkg/mod/github.com/liangdas/mqant@v1.4.12/rpc/base/rpc_server.go:203
	1  0x00000000016ecc31 in github.com/liangdas/mqant/rpc/base.(*RPCServer).runFunc·dwrap·2
	    at /Users/jerrylu/go/pkg/mod/github.com/liangdas/mqant@v1.4.12/rpc/base/rpc_server.go:411

**Comment by ShiXiangJiTuan** [comment]
😁

**Comment by Meng-Xin** [comment]
我这里是报了一个栈溢出，不清楚为什么导致的
