### ISSUE TITLE
如何在嵌入式设备上接收消息

### ISSUE THREAD

**Issue by nathubs** [liangdas/mqant#120]
大神你好，mqant目前不支持mqtt订阅功能，如何在嵌入式设备中接收消息，就是不使用mqantlib.js库如何收消息？多谢了

**Comment by liangdas** [comment]
嵌入式设备用的c语言吧，看看能不能不使用mqtt订阅功能就满足需求，我的理解只要能全双工通信就可以了，没必要一定奥支持订阅功能
