### ISSUE TITLE
app.NewApp(opts...)  ---> app.go 文件中解析配置文件有一个Bug

### ISSUE THREAD

**Issue by Meng-Xin** [liangdas/mqant#121]
```golang
	defaultConfPath := fmt.Sprintf("/%s/bin/conf/server.json", ApplicationDir)  //原代码
	defaultConfPath := fmt.Sprintf("%s/bin/conf/server.json", ApplicationDir)   //修改后
```

`/` **导致在调用Open()函数的时候一直报错，提示** 
`panic: config path error open /E:\Code\Go\study\lixiaoming/bin/conf/server.json: The filename, directory name, or volume label syntax is incorrect.`
把前面的`/`删除之后就正常启动实例Demo了

**Comment by liangdas** [comment]
嗯嗯感谢提交这个问题

**Comment by Meng-Xin** [comment]
请问有学习交流群吗？ 想学习一下

**Comment by Meng-Xin** [comment]
目前在网上没有找到太多关于Mqant相关的资料，只有一篇您写的文档，哈哈我想参考更多的写法或者使用的技巧
