### ISSUE TITLE
请教关于该框架使用和思路方面

### ISSUE THREAD

**Issue by Millyn** [liangdas/mqant#122]
你好，我是一名 web 开发者对于游戏开发不是很了解，看 mqant 的代码目前也是很懵，想到一些问题无从解决。

所以想咨询几个思路方面的问题。

1. 该如何鉴别一个用户是否有效，我们发现 mqtt 可以走 username / password 鉴权但游戏机制并不是游戏用户都有账号密码，这样该怎样处理？比如微信登入，Apple 账号登入 这些都只是有一个 unionID。
2. 怎么样判断客户端订阅的 topic 是合法的？ 比如目前想到用户订阅规则是 user/{userId} 有没有办法禁止 id 1 订阅和发布到 id 2 的 topic ？
3. 整个 mqtt 是不是这样的关系   用户客户端（手机）— MQTT Broker — 服务端客户端（业务逻辑）也就是说 实际上 服务端也是一个客户端？
4. 如果 3. 成立，那么服务端客户端如何知道用户下线而取消订阅？
5. 如果 3. 成立，那么问题 1 里所说的登入服务端的客户端该如何鉴权登入？

**Comment by liangdas** [comment]
mqant里面用的通常是长链接，在一个tcp连接建立以后我们可以要求客户端提交鉴权，鉴权成功后我们可以通过session给这条链接赋予用户身份信息，以后的topic请求就都可以根据实际情况校验用户身份，也就是每一条连接都需要鉴权，然后这条连接绑定上用户身份
