### ISSUE TITLE
session里面的TraceId和SpanId 设计目的和用途分别是什么，文档没看到相关资料

### ISSUE THREAD

**Issue by fengzii** [liangdas/mqant#124]
主要是协议统一的问题
RegisterGO注册的函数 响应给客户端是 app.resultInfo
type resultInfo struct {
	Trace  string
	Error  string      //错误结果 如果为nil表示请求正确
	Result interface{} //结果
}
session.Send发送是[]byte 两边协议不统一，得自己封装

**Comment by liangdas** [comment]
TraceId和SpanId 是日志跟踪ID，在日志里面打印上方便串联这次请求的日志
