### ISSUE TITLE
关于http网关的问题

### ISSUE THREAD

**Issue by fengzii** [liangdas/mqant#126]
在httpgate模块启动一个http服务，并设置Handler: httpgateway.NewHandler(self.App)
然后在helloworld模块 OnInit 注册对应的方法 
    self.GetServer().RegisterGO(" /helloworld/topic", self.topic)
    self.GetServer().RegisterGO(" /topic", self.topic)

去请求 http://localhost:8090/helloworld/topic
就会提示
"Remote function(/helloworld/topic) not found"
然而在tcp网关上请求helloworld注册的方法 是ok的

这是为何 ？

**Comment by chainheader** [comment]
为何？？？？
