### ISSUE TITLE
RPC支持可变长参数的问题

### ISSUE THREAD

**Issue by hellolw** [liangdas/mqant#14]
这几天首次使用MQANT提供的RPC，发现不支持可变长参数。
如果注册的RPC使用了可变长参数，那么调用时可能会出现如下打印
The number of params %s [%d] is not adapted.%s [%d]

检查了代码，在
func (s *RPCServer) runFunc(callInfo mqrpc.CallInfo, callbacks chan<- mqrpc.CallInfo) 函数中有如下判断

if len(params) != f.Type().NumIn() {
			//因为在调研的 _func的时候还会额外传递一个回调函数 cb
			_errorCallback(callInfo.RpcInfo.Cid, fmt.Sprintf("The number of params %s [%d] is not adapted.%s [%d]", params, len(params), f.String(), f.Type().NumIn()), nil)
			return
		}
由此可见，可变长参数是不支持的。
我简单修改了一下，
if f.Type().IsVariadic() {
		if len(params) < f.Type().NumIn() {
			_errorCallback(callInfo.RpcInfo.Cid, fmt.Sprintf("1 The number of params %s [%d] is more than .%s [%d]", params, len(params), f.String(), f.Type().NumIn()), nil)
			return
		} 
	} else {
		if len(params) != f.Type().NumIn() {
			//因为在调研的 _func的时候还会额外传递一个回调函数 cb
			_errorCallback(callInfo.RpcInfo.Cid, fmt.Sprintf("The number of params %s [%d] is not adapted.%s [%d]", params, len(params), f.String(), f.Type().NumIn()), nil)
			return
		}
	}
目前这样的修改是能满足我的需求。不知道群主有什么好的建议。

PS：不用可变长参数的话，可以直接使用一个string类型做参数，在调用RPC前后，在程序中通过json编解码要传递的参数，然后再转成string，只是感觉这样有点麻烦

**Comment by liangdas** [comment]
非常感谢你提这个功能，golang本身不支持可变参数(golang是比较严格的语言,可变参数可能会引起一些不确定性吧)，所有当时也没有考虑这个问题，不过还是希望你能把代码提上来，加入我们的QQ交流群 :463735103。讨论一下这个功能，如果有必要就合进主分支

**Comment by hellolw** [comment]
Hi,

怎么提交代码了？我修改的，就是我贴在issue里面的那一段，仅仅加了个IsVariadic的判断，分别处理两种情况。我是go和游戏的新人，不确定这样做是否合适。
PS：已经加了群了。默默的看着你们讨论那些我看不懂的高深问题（捂脸）

**Comment by liangdas** [comment]
用的时候如何使用呢？

**Comment by hellolw** [comment]
注册RPC，
func (this *module)  func1(para1 string, para2 string, paras ...*my_struct) (result string, err string) {
}

this.GetServer().RegisterGO("func1", self.func1)
调用RPC，
_, error_code := self.RpcInvoke("module", "func1", "DB", "TABLE", param1, param2, param3, param4, param5)
后面的parameter数目不定。
我是用作数据库操作的，不同的表，给定的参数不同，所以希望能有可变数目的参数。
按照我的这个调用方法，原来RPC实现时，会认为传入参数个数（7）大于函数给定参数数目（3），而发生错误，导致RPC调用失败。

**Comment by liangdas** [comment]
好的，那我测试一下这个功能，主要看后面的可变参数的参数类型如果不同的话应该怎么来使用，如果没有问题可以合进来

**Comment by hellolw** [comment]
可变参数类型不同是没法用的，毕竟RPC的参数不能直接用interface()

**Comment by liangdas** [comment]
我试了一下para ... struct_type 可以是rpc支持的不同类型，不过使用的时候需要去强转，这个功能暂时先不加吧，容易造成混乱，毕竟调用接口的时候如果多传一个为止参数就会造成未知的影响，增加了调试成本。
你做一个DB操作的功能我个人认为有点危险，很容易被滥用最后暴露一些SQL注入漏洞等问题

**Comment by hellolw** [comment]
SQL注入 这个确实没有考虑。
在注册的RPC函数中对于入参做了简单的判断，可以规避一部分SQL注入漏洞，但是应该还是会有漏洞的。
新手，还需要大神多多指导，多给意见，hehe
