### ISSUE TITLE
使用封装的MQTT通信时，TOPIC为什么必须含有HD，请问这个可以自定义吗

### ISSUE THREAD

**Issue by Creat-qc** [liangdas/mqant#142]
如题目

**Comment by Creat-qc** [comment]
没有找到HD相关的功能代码，up可以解释一下吗

**Comment by liangdas** [comment]
可以不用HD开头了，已经移除了相关代码，现在可以定义你自己的topic路由协议，现在内置了一个uri路由协议
uriroute.NewURIRoute

//注意这里一定要用 gate.Gate 而不是 module.BaseModule
	this.Gate.OnInit(this, app, settings,
		gate.Heartbeat(time.Second*5),
		gate.BufSize(2048*20),
		**gate.SetRouteHandler(this),**
		gate.SetSessionLearner(this),
		gate.SetStorageHandler(this),
		gate.MaxPackSize(65535*2),
	)

**Comment by Creat-qc** [comment]
好的，多谢前辈，之后研究下，是对应在线文档中的  **自定义通讯协议**小节吗

**Comment by Creat-qc** [comment]
前辈，之前设置 HD 是有其他地方的考量吗，怕冲突吗？不太了解这块，所以想问下之前设计的用意

**Comment by liangdas** [comment]
为了隔离c-s通讯和s-s接口，如果不隔离担心客户端请求服务端的私有接口，有安全风险
