### ISSUE TITLE
客户端使用M2Mqtt连接MqantSrever，Read login pack error

### ISSUE THREAD

**Issue by jjjjilyf** [liangdas/mqant#21]
[mqant_agent.go:94]Read login pack error%!<EXTRA *errors.errorString=IDentifier Rejected length is:36>
github.com/lingdas/mqant/gate/base/mqant_agent.go 94
github.com/lingdas/mqant/network/tcp_server.go:95

**Comment by liangdas** [comment]
目前mqant只支持mqtt v3 版本也就是 MQTT 3.1
v3版本是MQTT 3.1.1
因此在使用库的时候要注意选择

ProtocolVersion = MqttProtocolVersion.V3_1, //设置为V3_1

http://www.mqant.com/topic/5942638453ad5d474f7eae12

**Comment by jjjjilyf** [comment]
Thanks a lot。
