### ISSUE TITLE
使用vendor进行包管理

### ISSUE THREAD

**Issue by memwey** [liangdas/mqant#27]
Hi,
不好意思,又是我
目前项目这种包管理的方式不太方便,也容易引起一些问题.Golang自1.5后提供了比较方便的vendor进行项目的包管理,也是类似与将依赖加入到项目目录下,了解一下
另外,官方的包管理工具dep也很好用

**Comment by liangdas** [comment]
嗯嗯最近我也在研究dep,因为golang官方也要推出包管理工具,不过目前好像还不完善，我想等稳定了再统一移植过去

**Comment by Alex-liutao** [comment]
建议不要使用 `dep` 和 `vendor`，理由可以参考 [Russ Cox 的解答](https://github.com/golang/go/issues/24301#issuecomment-371228664)

现在我做的项目是在 mqantserver 的基础上改动的，这个项目做成一个了 module，然后用 go modules 的机制来管理所有的依赖。

这里有个问题，假如我项目叫 **Proj1**，已经把它初始化为一个 module 了，在项目的目录上运行新版本的 `go get github.com/liangdas/mqant`，它会自动获取 mqant 包最近一次 tag 过的版本（即 1.6.7）。但是这个版本的的 mqant 由于同时导入的两个不同路径的 redigo 包，导致编译失败。

目前我的解决方案是，为了能够编译通过，在引用到 mqant 的 module 上，运行 `go get github.com/liangdas/mqant@4d9ab43` 其中的 `4d9ab43` 代表最新一次 commit 的 hash。通过这样来强行指定不让 go get 自动获取到 v1.6.7 的版本。

建议的解决方案，在 v1.6.7 版本的基础上，把所有引用到 `github.com/garyburd/redigo` 包的地方，全部替换为 `github.com/gomodule/redigo`，然后添加一个 v1.6.8 的标签，推送到 GitHub 上。这样，当别的 module 导入 mqant 包时，就会自动获取 v1.6.8 版本，并且编译能够顺利进行。

**Comment by liangdas** [comment]
多谢提醒，我这边打一个v1.6.8的tag，现在golang的包管理确实混乱，更多依靠开发者的技术分辨水平
