### ISSUE TITLE
关于ws_conn读取可能会卡的问题

### ISSUE THREAD

**Issue by brantlane** [liangdas/mqant#32]
测试publish稍微大点的数据（字符串过千）的时候，会出现非常长的超时。调试代码发现wc_conn中的read可能有问题，导致chan等待。当然，注释也写了goroutine不安全。哈哈。

// goroutine not safe
func (wsConn *WSConn) Read(p []byte) (n int, err error) {
	err = <-wsConn.buf_lock //等待写入数据
	if err != nil {
		//读取数据出现异常了
		return
	}
	if wsConn.buffer.Len() == 0 {
		//再等一次
		err = <-wsConn.buf_lock //等待写入数据
		if err != nil {
			//读取数据出现异常了
			return
		}
	}
	return wsConn.buffer.Read(p)
}

**Comment by liangdas** [comment]
应该是buffer设置的缓冲区比你发的数据小造成的

**Comment by brantlane** [comment]
恩，调大缓冲是可以解决问题。但是这个大小的设定有没有什么依据？

**Comment by liangdas** [comment]
根据游戏类型，每次传送数据量大小来定吧，设置得大了占服务端内存多

**Comment by brantlane** [comment]
ok。先这样。

**Comment by Linnkenn** [comment]
确认一下，
1：看代码是否MaxMsgLen 只对ws连接起作用？
2：MqttAgent的读写buffer的大小默认为1024，当数据量大的时候需要将该大小设置更大是吧？

**Comment by Linnkenn** [comment]
> 2：MqttAgent的读写buffer的大小默认为1024，当数据量大的时候需要将该大小设置更大是吧？
> 网络通信数据量比较大，buffer就要设置更大一些

是否将配置文件中的MaxMsgLen设为buffer的read， write 大小更好一些？
