### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LonelySnail** [liangdas/mqant#33]
每个客户端连接上来 会开两个协程 去接收客户端信息和 向客户端写入信息，但客户端断开之后 这两个协程不会关闭，造成内存浪费

**Comment by liangdas** [comment]
有解决的方案吗？有的话提供一下

**Comment by LonelySnail** [comment]
可在liangdas/mqant/gate/base/mqtt/pack_queue.go   119行 加上  break loop 就可以了

**Comment by liangdas** [comment]
已加上，多谢
