### ISSUE TITLE
session.GetUserid undefined 

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#34]
在編譯mqantserver時，會發生session.GetUserid undefined和session.TracCarrier undefined  等許多錯誤

**Comment by liangdas** [comment]
1.8.0版本对这些接口做了修改，mqantserver我刚也更新了，都重新更新到最新吧

**Comment by liangdas** [comment]
1.8.0版本对这些接口做了修改，mqantserver我刚也更新了，都重新更新到最新吧
