### ISSUE TITLE
使用mqantserver\Xaxb時發生錯誤

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#36]
執行robot測試Xaxb時，會出現
`[unified_send_message_table.go:187] SendBatch error Gate001 The number of params
76af5dae5d20d45b,d9ea7c0ca55872b9
XaXb/OnStop
[{"Coin":100000,"Rid":"","SeatIndex":0,"SitDown":true,"Stake":false,"Target":0,"Weight":0},{"Coin":100000,"Rid":"","SeatIndex":1,"SitDown":true,"Stake":false,"Target":0,"Weight":0}]
is not adapted.<func(log.TraceSpan, string, string, []uint8) (int64, string) Value>`
請問是哪裡出錯，使用mqantserver檔案，並未修改任何程式

**Comment by liangdas** [comment]
新增了一个log.TraceSpan,

**Comment by liangdas** [comment]
更新一下https://github.com/liangdas/mqant-modules库

**Comment by shihray** [comment]
謝謝，更新完後可以運行了
