### ISSUE TITLE
關於配桌方式

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#37]
目前使用room.GetUsableTable()來配桌
但是在mqantserver中有說到目前這方法還不智能
若要更改，請問要重哪裡下手呢?

**Comment by liangdas** [comment]
直接看room模块源码就行，自己改，这个模块不复杂，理解原理后就按自己的需求改

**Comment by shihray** [comment]
不好意思，可以再請教一個問題
如何獲得該房間是否有空位?

**Comment by liangdas** [comment]
房间是否有空位是由房间内逻辑决定的，房间内写一个查询函数就行
