### ISSUE TITLE
mqtt server 这块逻辑在哪呢？一直没找到

### ISSUE THREAD

**Issue by zhengchengbin610** [liangdas/mqant#45]
你好，
   我本来是想找个go 的 mqtt server，但是发现很多都是要么不维护，要么很臃肿，我想代码控制，自己来处理这个框架，所以找到这个开源库，但是一直找不到mqtt相关代码，希望可以协助

**Comment by liangdas** [comment]
mqtt的相关代码在 gate模块里面
