### ISSUE TITLE
如何单独使用网关模块

### ISSUE THREAD

**Issue by zhengchengbin610** [liangdas/mqant#46]
你好，我想单独使用网关模块，应用在智能家居里面，是否可以指点一二？

**Comment by liangdas** [comment]
单独使用网关模块可能没有啥意义吧,市面上有很多标准的mqtt网关服务，mqant的意义在于可以自定义mqtt的后端服务,不必遵循mqtt标准的订阅发布协议

**Comment by zhengchengbin610** [comment]
@liangdas 非常感谢回复，我是想智能家居以mqtt协议接入，市面上的mqtt网关服务，本来我是想找个go比较健全和稳定的mqtt broker ,发现也很少，其他语言倒是挺多的；因为如果单独部署一个Mqtt服务器，不能像与用户直接关联进行控制，我发现mqant就可以做到，所以才想是否可以把mqant网关层拿出来用；你对我的场景有什么建议么？

**Comment by liangdas** [comment]
你这个需求就是对mqtt协议进行更加个性化的需求了，那mqant框架本身就能做到，gate是mqtt协议层，然后你们通过topic定制自己的路由规则路由到后端其他mqant模块进行各个业务的访问，在mqant各个业务模块对用户行为进行控制即可，这点跟用mqant进行游戏开发类似

**Comment by zhengchengbin610** [comment]
@liangdas 首先谢谢回复，你说的的确是可以，但是对这个mqant需要花不少时间来熟悉，目前我按照你之前说的找了一个mqtt服务，只做数据转发协议，其他服务与mqtt服务之间通过Mqtt 连接池来进行交互
