### ISSUE TITLE
教程文件有一点乱

### ISSUE THREAD

**Issue by iKuiki** [liangdas/mqant#49]
就我所找到的教程包括wiki和example，wiki里的介绍太分散了，没有系统性，就每个小模块可能都说了，但是没有把他们穿起来
然后example虽然有，但一下就那么复杂不理解为何要如此
建议：
写一个入门教程，就一步步怎么把example写出来，每一步用意是什么（不需要现在的example那么复杂的，只需要把各个模块都用一下就好了，实现一个聊天室功能就OK了

**Comment by liangdas** [comment]
嗯嗯好建议
