### ISSUE TITLE
有与其它游戏框架的优缺点对比吗？

### ISSUE THREAD

**Issue by isghost** [liangdas/mqant#5]
和pomelo ,kbengine, scut相比有什么优点。如果现在没有，将来计划会有什么优点吗？
或者在某些游戏类型上有什么显著优点。或者这个框架更偏向skynet?

**Comment by liangdas** [comment]
这篇文章我有说明https://github.com/liangdas/mqant/wiki/mqant%E7%9A%84%E8%AE%BE%E8%AE%A1%E5%8A%A8%E6%9C%BA

mqant下一步还会计划做python版本的辅助版本,实现golang语言与python语言结合开发，例如用golang做核心的游戏逻辑功能，python做web端,用户登录校验API等，python和golang可以轻松的实现通信

**Comment by isghost** [comment]
我现在在学习pomelo，js语言和回调太多的缺陷太明显。好处是易于学习。期待mqant能做到用python写逻辑...简单易上手

**Comment by liangdas** [comment]
python是辅助，mqant不会再golang上面加一个python解析器，而是会做一套python简版的pymqant，这样在项目里面可以根据不同模块功能选择适合的开发语言，最后还能实现模块间无缝的通信
