### ISSUE TITLE
mqantserver编译出错

### ISSUE THREAD

**Issue by sonwa** [liangdas/mqant#53]
使用mqant2X库，在mqantserver编译出错

# server/gate
gate/CustomAgent.go:113:26: this.gate.GetMinStorageHeartbeat undefined (type gate.Gate has no field or method GetMinStorageHeartbeat)
gate/CustomAgent.go:116:72: cannot use this.GetSession().GetUserId() (type string) as type gate.Session in argument to this.gate.GetStorageHandler().Heartbeat:
	string does not implement gate.Session (missing Bind method)
gate/module.go:53:29: cannot use gate (type *Gate) as type gate.StorageHandler in argument to gate.Gate.SetStorageHandler:
	*Gate does not implement gate.StorageHandler (wrong type for Delete method)
		have Delete(string) error
		want Delete(gate.Session) error
gate/module.go:54:11: gate.Gate.SetTracingHandler undefined (type basegate.Gate has no field or method SetTracingHandler)

**Comment by liangdas** [comment]
更新一下mqant主库

**Comment by sonwa** [comment]
还有错误，编译不到

# server/helloworld
helloworld/module.go:12:2: imported and not used: "github.com/liangdas/mqant/selector"
helloworld/module.go:13:2: imported and not used: "sync"
helloworld/module.go:14:2: imported and not used: "github.com/liangdas/mqant/registry"
helloworld/module.go:15:2: imported and not used: "math/rand"
# server/gate
gate/CustomAgent.go:116:72: cannot use this.GetSession().GetUserId() (type string) as type gate.Session in argument to this.gate.GetStorageHandler().Heartbeat:
	string does not implement gate.Session (missing Bind method)
gate/module.go:54:29: cannot use this (type *Gate) as type gate.StorageHandler in argument to this.Gate.SetStorageHandler:
	*Gate does not implement gate.StorageHandler (wrong type for Delete method)
		have Delete(string) error
		want Delete(gate.Session) error

**Comment by QiMa** [comment]
gate/CustomAgent.go:116:72: 的this.GetSession().GetUserId() 去掉.GetUserId()
gate/CustomAgent里的Delete(string)改为Delete(gate.Session)
引擎接口参数版本改了，server代码没相更新，也有可能大帅忘了上传最新的

**Comment by sonwa** [comment]
可以了
gate/module.go都把Storage、Delete、Heartbeat参数的string改成gate.Session就行了
