### ISSUE TITLE
配置問題

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#55]
請問在 [配置差异](https://github.com/liangdas/mqant/wiki/mqant1x与2x的差异#配置差异)當中有提到現在會自動註冊 `module id`
若有多組module (ex. XaXb部屬兩個)
想請問現在 `client端`連進來後會導向到哪台，要如何指定
還是 `v2`並不需要指定，會自動分配loading??

**Comment by liangdas** [comment]
对v2版本以后module id 自动分配了，可以在module里面通过ServerId获取，然后自己在想办法通知给前端

**Comment by shihray** [comment]
那請問大神可否解說一下
```
app.Options().Selector.Init(selector.SetStrategy(func(services []*registry.Service) selector.Next {
		var nodes []*registry.Node

		// Filter the nodes for datacenter
		for _, service := range services {
			for _, node := range service.Nodes {
				if node.Metadata["type"] == "helloworld" {
					nodes = append(nodes, node)
				}
			}
		}

		var mtx sync.Mutex
		//log.Info("services[0] $v",services[0].Nodes[0])
		return func() (*registry.Node, error) {
			mtx.Lock()
			defer mtx.Unlock()
			index := rand.Intn(len(nodes))
			return nodes[index], nil
		}
	}))
```
> `node.Metadata["type"] == "helloworld" `
這要如何配置?

module裡面需要在 `init`裡面設定才會對應到嗎?

**Comment by liangdas** [comment]
https://github.com/liangdas/mqant/wiki/mqant2x%E7%9A%84%E6%89%A9%E5%B1%95#%E6%9B%B4%E6%96%B0%E5%85%83%E6%95%B0%E6%8D%AE
