### ISSUE TITLE
Gate  OnRecover error [invalid argument to Intn] 出错问题

### ISSUE THREAD

**Issue by sonwa** [liangdas/mqant#59]
登录时出现Gate  OnRecover error [invalid argument to Intn] 
github.com/liangdas/mqant/gate/base/mqtt_agent.go:212
请问是什么问题？
gnatsd和consul都有运行

![1560156747983](https://user-images.githubusercontent.com/1425134/59184302-6f4f3180-8ba0-11e9-813f-d47d7943d8df.jpg)

**Comment by liangdas** [comment]
请下载一下最新的mqant 库，我把错误堆栈打印出来了，方便定位问题

**Comment by sonwa** [comment]
打印到了

<img width="1002" alt="屏幕快照 2019-06-11 下午2 02 01" src="https://user-images.githubusercontent.com/1425134/59247349-a5002300-8c51-11e9-91b6-abb188f1b6e3.png">

**Comment by liangdas** [comment]
原因应该是main.go 里面 index := rand.Intn(len(nodes)) 的问题 更新一下mqantserver试试

app.Options().Selector.Init(selector.SetStrategy(func(services []*registry.Service) selector.Next{
		var nodes []*registry.Node

		// Filter the nodes for datacenter
		for _, service := range services {
			for _, node := range service.Nodes {
				if node.Metadata["type"] == "helloworld" {
					nodes = append(nodes, node)
				}
			}
		}

		var mtx sync.Mutex
		//log.Info("services[0] $v",services[0].Nodes[0])
		return func() (*registry.Node, error) {
			mtx.Lock()
			defer mtx.Unlock()
			index := rand.Intn(int(len(nodes)))
			return nodes[index], nil
		}
	}))

**Comment by liangdas** [comment]
如果还不行就屏蔽掉吧

**Comment by sonwa** [comment]
更新了都不行，但你说屏蔽了
app.Options().Selector.Init(selector.SetStrategy(func(services []*registry.Service) selector.Next{
		var nodes []*registry.Node
........

这段就行了。屏蔽了会有什么影响吗？

**Comment by liangdas** [comment]
那就屏蔽掉吧index := rand.Intn(int(len(nodes))) 随机取模有问题

**Comment by sonwa** [comment]
屏蔽了会对集群方面有没有影响？没屏蔽发“helloworld/HD_Say”看见是有效果是过滤掉没出错的，但发其它会出错。

**Comment by liangdas** [comment]
没有影响，就是一个自定义的节点选择器示例

**Comment by sonwa** [comment]
我看文档
app.Options().Selector.Init(selector.SetStrategy(func(services []*registry.Service) selector.Next
......
是全局默认规则设置，不设这个系统都会自动选最优的节点通信的吗？

**Comment by liangdas** [comment]
默认的规则就是随机节点，没有自动选择最优
