### ISSUE TITLE
给您泼盆冷水，这个很难实现分布式，只是rpc，因为节点会话转发和节点选优、负载均衡没有解决。

### ISSUE THREAD

**Issue by 631768417** [liangdas/mqant#6]
x

**Comment by liangdas** [comment]
你说的这些问题,有些问题目前都还确实存在，但有些已解决了,可能你还不清楚
1. 节点选优
    已留给开发者自己选择,有一个回调接口开发者自己可以重载以实现自己的节点选择方案,目前框架默认是按userId取模来选择的

2. 节点会话转发
      这个我不清楚是神马功能，从gate可以直接连通后端所有的进程模块,为何需要转发? 节点间通信直接通过rpc也可以互通

3. 负载均衡
     这个框架本身没有实现,不过rpc基于rabbitmq本身也自带负载均衡工,mqant模块是ator模型,也可称为工作队列模式吧,一个模块会根据他自己的能力获取rabbitmq队列里面的消息,当处理能力受限的时候消息会积压在rabbitmq中,等有能力的时候再消费,因此完全可以对压力大的模块新增一个节点,接收同一个队列里面的消息,这样就能负载均衡了

最后目前框架还有很多功能没有完善,例如服务发现等。但我自己的服务目前已经搭起来了，目前只是固定几台机器,如果要增加机器的话需要重启所有进程,不过目前对我的项目来说还能接受。非常感谢你能提出你的一些想法,也希望你能够深入的了解这个框架,其中有些功能可能是只实现了核心,灵活变通就可以实现正式的需求

**Comment by Linnkenn** [comment]
> 你说的这些问题,有些问题目前都还确实存在，但有些已解决了,可能你还不清楚
> 
> 1. 节点选优
>    已留给开发者自己选择,有一个回调接口开发者自己可以重载以实现自己的节点选择方案,目前框架默认是按userId取模来选择的
> 2. 节点会话转发
>    这个我不清楚是神马功能，从gate可以直接连通后端所有的进程模块,为何需要转发? 节点间通信直接通过rpc也可以互通
> 3. 负载均衡
>    这个框架本身没有实现,不过rpc基于rabbitmq本身也自带负载均衡工,mqant模块是ator模型,也可称为工作队列模式吧,一个模块会根据他自己的能力获取rabbitmq队列里面的消息,当处理能力受限的时候消息会积压在rabbitmq中,等有能力的时候再消费,因此完全可以对压力大的模块新增一个节点,接收同一个队列里面的消息,这样就能负载均衡了
> 
> 最后目前框架还有很多功能没有完善,例如服务发现等。但我自己的服务目前已经搭起来了，目前只是固定几台机器,如果要增加机器的话需要重启所有进程,不过目前对我的项目来说还能接受。非常感谢你能提出你的一些想法,也希望你能够深入的了解这个框架,其中有些功能可能是只实现了核心,灵活变通就可以实现正式的需求

关于第三点负载均衡，新增一个节点，接收同一个队列里面的消息，具体是如何操作的？新增一个ProcessID的进程，里面新加一个相同模块，并且共用一个队列？
