### ISSUE TITLE
关于扩容的疑问

### ISSUE THREAD

**Issue by qiangv** [liangdas/mqant#62]
原先是做端游，初入H5游戏开发，发现了这个仓库，很棒！
游戏框架的逻辑我学习了下，有个疑问，当出现负载问题的时候，如何进行动态扩容呢？
我的设想是做一系列的H5游戏，一个游戏启动一个docker，N个游戏N个docker，有一个网关负责分配用户到特定的游戏docker里，当不足的时候进行扩容，然后有一个GM端可以进行管理，但总觉得怪怪的，不知道这个你有什么指导的么？

**Comment by qiangv** [comment]
我看到支持模块分布式，是不是意味着我对游戏A扩容，游戏B扩容。这个带来一个疑问，我如何管理游戏A的1、2、3...N个扩容模块的数据呢，不知道我的理解对不对。

**Comment by liangdas** [comment]
如何管理你的数据是你游戏架构设计的工作，框架保证是分布式的，可以很容易实现各个模块相互通信。
