### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by TianQingS** [liangdas/mqant#63]
rpc_server里面每一个注册的Go函数都启动一个新的gorountine，为什么不用chan的方式启动固定个数rountine呢？
另外，demo示例中使用的无锁队列有严重bug，当get请求远大于put请求时，容量计算会错误，导致卡死。

**Comment by liangdas** [comment]
rpc_server 里面的gorountine 数量是可以通过参数控制的

demo示例中使用的无锁队列有严重bug，当get请求远大于put请求时，容量计算会错误，导致卡死。这是这个问题可以再说具体一点吗？

**Comment by TianQingS** [comment]
1、if functionInfo.Goroutine {
		go _runFunc() // 这里每次都新建gorountine，感觉会不会比固定几个routine，通过chan方式传过去执行消耗大一些。
	} else {
		_runFunc()
	}
2、	if putPos >= getPos {
		posCnt = putPos - getPos
	} else {
		posCnt = capMod + (putPos - getPos) 
	}

	if posCnt >= capMod-1 { // 有多个get会有概率先把getPos加成超过putPos，即使队列没有数据也会出现getPos比putPos大1或者相等情况。这里无法新插数据，get也在无限等待put。
		runtime.Gosched()
		return false, posCnt
	}

**Comment by liangdas** [comment]
我不记得那个demo里面有
2、	if putPos >= getPos {
posCnt = putPos - getPos
} else {
posCnt = capMod + (putPos - getPos)
}
相关的代码啊

**Comment by liangdas** [comment]
协成数量这块以后会考虑加协成池

**Comment by TianQingS** [comment]
不是demo的，是demo引用的那个高性能无锁队列的
