### ISSUE TITLE
mqant執行時會出現 nats: invalid subscription

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#70]
mqant 正常執行一段時間後
會跳出 `NatsServer error with 'nats: invalid subscription'`
請問為什麼會出現該問題 ?

**Comment by liangdas** [comment]
可能nats重连了，这个我做了一下优化故意打出来，你可以测试目前rpc是否还可正常使用

**Comment by shihray** [comment]
動作還是正常的
只是會不定時出現  想知道該部分要如何優化?

**Comment by liangdas** [comment]
那应该是重连了,不需要管

**Comment by shihray** [comment]
好的 謝謝大神

**Comment by shihray** [comment]
目前發現 若觸發 `NatsServer error with 'nats: invalid subscription' `
gateway session error : `fatal error: concurrent map read and map write`
讀寫問題發生在 
```
mqant/gate/base/mqtt_agent.go:309

b, err := session.Serializable()
```

**Comment by liangdas** [comment]
用的最新的mqant版本吗？我记得我修复过

**Comment by shihray** [comment]
目前是用 v1.1.16版本
可以請問是在哪次更新修復的嗎? 我去確認一下檔案

**Comment by liangdas** [comment]
我再看看是不是上次把这个修改删除了，好像记得上次修改后因为锁问题删除了

**Comment by shihray** [comment]
目前使用 goroutine 故意觸發讀寫問題
目前session機制 無法有效阻擋 該情況發生
將 `RWMutex` 改回 `Mutex` 發現該情況才可以避免  
不確定是否正確 提供參考

**Comment by liangdas** [comment]
你可以发一下你的方案给我瞧瞧

**Comment by liangdas** [comment]
func (this *sessionagent) Serializable() ([]byte, error) {
	this.lock.Lock()
	defer this.lock.Unlock()
	data, err := proto.Marshal(this.session)
	if err != nil {
		return nil, err
	} // 进行解码
	return data, nil
}我就打算这么加一下

**Comment by shihray** [comment]
我也是將 lock 參數改回 sync.Mutex 測試看看
但改後會在 ` Serializable()`併發讀寫問題
也有在裡面加過lock 但情況沒有改善

**Comment by liangdas** [comment]
我刚更新了一个1.1.17版本你试试看

**Comment by shihray** [comment]
剛壓力測試 發現是 session Clone() 動作後 執行  session.Serializable() 會併發讀寫問題喔

**Comment by liangdas** [comment]
v1.1.18已经修复这个问题了

**Comment by Tangkysin** [comment]
v1.4.10
启动后客户端马上请求就会出现 NatsClient error with 'nats: invalid subscription'。
等一会或者请求报错后再次请求就没有了。
