### ISSUE TITLE
关于2x和文档

### ISSUE THREAD

**Issue by github-yxb** [liangdas/mqant#71]
看文档里不少地方出现关于2x版本的描述，但是release里并没有2x版本，是因为还没开发好吗？  
我觉的2x版本的服务注册和发现才是趋势，现在的1.x方式配置管理复杂，不太友好.  
还有文档略零散，想看关于分布式部署还得摸代码。

**Comment by liangdas** [comment]
因为golang 1.13以后go mod强制要求使用major版本规则，mqant目前还不需要，因此只能先将版本号回退为v1.x

功能是最新的只是版本号回退了，服务注册和发现功能是有的，可以参考gomicro的api
