### ISSUE TITLE
Gate 觸發 the work queue is full

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#72]
執行一段時間後 觸發
[mqtt_agent.go:205] Gate OnRecover error [the work queue is full!] 
請問是有哪邊需要調整嗎?

**Comment by liangdas** [comment]
this.Gate.OnInit(this, app, settings,
		
		gate.ConcurrentTasks(10),
		
	)
主要原因还是你客户端发送数据太快了，后端处理不过来

**Comment by shihray** [comment]
顧名思義 我設定越大 機器設備就需要越好嗎?
我看預設是20 請問設定越大對mqant會有哪些影響

**Comment by liangdas** [comment]
gate.ConcurrentTasks(10), 代表后端每一个客户端节点可同时处理的协程数，设置过高可能协程数量也会提高，具体原因可以分析一下是不是客户端某一类请求响应过慢导致的

**Comment by shihray** [comment]
感謝大大
