### ISSUE TITLE
mqant快速重啟後 RPC會找不到節點

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#73]
若將gate網關模塊與其他模塊拆開後
gate重啟後，會出現 `[nats_client.go:179] rpc callback no found : [2f54c3de-63da-4b9d-8fdc-7d816d50c151] `
的問題造成 無法與其他模塊溝通
這部分需修改那些地方 在重啟時重新註冊RPC

**Comment by liangdas** [comment]
重启的时候不要直接用kill -9 因为这样服务无法注销老的服务信息，注册中心需要15s才能感知，一定要优雅的退出,我目前的处理方式是通过在Metadata设置两个参数来控制节点流量，然后灰度下线重启

_ = app.Options().Selector.Init(selector.SetStrategy(func(services []*registry.Service) selector.Next {
		var nodes []WeightNode
		// Filter the nodes for datacenter
		for _, service := range services {
			for _, node := range service.Nodes {
				weight := 100
				if w, ok := node.Metadata["weight"]; ok {
					wint, err := strconv.Atoi(w)
					if err == nil {
						weight = wint
					}
				}
				if state, ok := node.Metadata["state"]; ok {
					if state != "forbidden" {
						nodes = append(nodes, WeightNode{
							Node:   node,
							Weight: weight,
						})
					}
				} else {
					nodes = append(nodes, WeightNode{
						Node:   node,
						Weight: weight,
					})
				}
			}
		}
		//log.Info("services[0] $v",services[0].Nodes[0])
		return func() (*registry.Node, error) {
			if len(nodes) == 0 {
				return nil, fmt.Errorf("no node")
			}
			rand.Seed(time.Now().UnixNano())
			//按权重选
			total := 0
			for _, n := range nodes {
				total += n.Weight
			}
			if total > 0 {
				weight := rand.Intn(total)
				togo := 0
				for _, a := range nodes {
					if (togo <= weight) && (weight < (togo + a.Weight)) {
						return a.Node, nil
					} else {
						togo += a.Weight
					}
				}
			}
			//降级为随机
			index := rand.Intn(int(len(nodes)))
			return nodes[index].Node, nil
		}
	}))

**Comment by shihray** [comment]
會遇到該狀況為mqant遇到錯誤直接中斷了
重啓時發生的問題
能否在每次啟動前重新註冊節點？

若要修改15s 重啓感知時間要修改哪個地方呢？

**Comment by liangdas** [comment]
func (self *admin_web) OnInit(app module.App, settings *conf.ModuleSettings) {
	self.BaseModule.OnInit(self, app, settings,
		server.RegisterTTL(5*time.Second),
		server.RegisterInterval(5*time.Second))
不建议这样做,这样会增加配置中心压力

**Comment by pandaju** [comment]
> 重启的时候不要直接用kill -9 因为这样服务无法注销老的服务信息，注册中心需要15s才能感知，一定要优雅的退出,我目前的处理方式是通过在Metadata设置两个参数来控制节点流量，然后灰度下线重启
> 
> _ = app.Options().Selector.Init(selector.SetStrategy(func(services []*registry.Service) selector.Next {
> var nodes []WeightNode
> // Filter the nodes for datacenter
> for _, service := range services {
> for _, node := range service.Nodes {
> weight := 100
> if w, ok := node.Metadata["weight"]; ok {
> wint, err := strconv.Atoi(w)
> if err == nil {
> weight = wint
> }
> }
> if state, ok := node.Metadata["state"]; ok {
> if state != "forbidden" {
> nodes = append(nodes, WeightNode{
> Node: node,
> Weight: weight,
> })
> }
> } else {
> nodes = append(nodes, WeightNode{
> Node: node,
> Weight: weight,
> })
> }
> }
> }
> //log.Info("services[0] $v",services[0].Nodes[0])
> return func() (*registry.Node, error) {
> if len(nodes) == 0 {
> return nil, fmt.Errorf("no node")
> }
> rand.Seed(time.Now().UnixNano())
> //按权重选
> total := 0
> for _, n := range nodes {
> total += n.Weight
> }
> if total > 0 {
> weight := rand.Intn(total)
> togo := 0
> for _, a := range nodes {
> if (togo <= weight) && (weight < (togo + a.Weight)) {
> return a.Node, nil
> } else {
> togo += a.Weight
> }
> }
> }
> //降级为随机
> index := rand.Intn(int(len(nodes)))
> return nodes[index].Node, nil
> }
> }))

这段代码在mqantserver的main.go里有，但是好像没有运行到？请问是要额外配置什么东西吗？

**Comment by liangdas** [comment]
Metadata可以在每一个模块注册一个专门的函数来进行控制，提前把节点流量关闭调
