### ISSUE TITLE
mqant框架在应用崩溃，手动关闭等情况下如何正确停机

### ISSUE THREAD

**Issue by imoyakin** [liangdas/mqant#76]
当软件退出等关闭操作时，如何让框架正确释放资源。
例如： 
通知consul进行节点的deregister操作

**Comment by liangdas** [comment]
不要用kill -9 强杀就行

**Comment by liangdas** [comment]
模块有几个生命周期函数，自己在那些函数里面做处理就行

**Comment by imoyakin** [comment]
明白。
现在关闭服务后，框架并没有向consul注销服务。我注意到你的代码中正在编写相关部分，我会在确定其工作后手动关闭这个issue。

**Comment by liangdas** [comment]
//OnDestroy Web模块注销方法
func (self *AntiAddiction) OnDestroy() {
	//一定别忘了关闭RPC
	self.GetServer().OnDestroy()
}
这样处理就行
