### ISSUE TITLE
DefineErrorLogFunc 使用方法

### ISSUE THREAD

**Issue by shihray** [liangdas/mqant#77]
請問有文件或範例可以說明一下  `v1.1.22` 版本中 DefineErrorLogFunc 的使用方法嗎?

**Comment by liangdas** [comment]
log.LogBeego().SetFormatFunc(logs.DefineErrorLogFunc(app.GetProcessID(),4))

## 格式化异常日志输出格式

    log.Error("@login_error",)
    log.Error("@login_error","login_error_code_1001")
    type test struct {
        AppId string
    }
    log.Error("@login_error","login_error_code_1002",map[string]interface{}{"user_id":123})
    log.Error("@login_error","login_error_code_1003",map[string]interface{}{"user_id":123},test{AppId:"9999"})
    
### 如何输出json格式日志

    @ 开头的format将被识别为json格式日志
    
    代表是结构化日志  format=event_id  可选 v0=sub_event_id v1=error_msg v2=error_report v3=event_params[map,struct] v4=rparam[map,struct] v5=context_param[map,struct]
    
    event_id 事件ID 可以为HTTP请求方法名,RPC请求方法名
    
    sub_event_id  子事件ID 方法中出现问题的逻辑点
    
    error_msg 错误信息 error信息即可
    
    error_report 错误报告 告知这个错误出现的原因和影响
    
    event_params 参数用于定位问题
    
    rparam 请求参数用于定位问题
    
    context_param 上下文参数
    
    log.Error("@login_error","login_error_code_1003","错误日志测试",map[string]interface{}{"user_id":123},test{AppId:"9999"})
    
    输出格式为
    
    {
        "error_msg": "错误日志测试",
        "event_id": "@login_error",
        "event_params": {
            "user_id": 123
        },
        "file": "improving-server.go:442",
        "formattime": "2019-12-31T14:27:11.445955+08:00",
        "level": "[E] ",
        "processid": "development",
        "rparam": {
            "AppId": "9999"
        },
        "stack": "\nUNKNOWN/improving-server.go:442\nUNKNOWN/app.go:219\nUNKNOWN/improving-server.go:444\nruntime/proc.go:203",
        "sub_event_id": "login_error_code_1003",
        "timestamp": 1577773631445955000,
        "trace_id": "",
        "trace_span": ""
    }
