### ISSUE TITLE
如何确定消息发送出去，客户端一定收到了？

### ISSUE THREAD

**Issue by Yajun312890225** [liangdas/mqant#92]
客户端直接关闭网络，服务端是不知道连接已经断开，此时服务端给客户端发的消息就存在丢失的问题，框架是否已经考虑了这个事情，还是在哪里需要设置一下，请指导

**Comment by liangdas** [comment]
框架没有考虑这种情况，如果想消息不丢需要自己做消息离线存储，消息回执等功能设计，这不在框架范畴之内

**Comment by Yajun312890225** [comment]
> 框架没有考虑这种情况，如果想消息不丢需要自己做消息离线存储，消息回执等功能设计，这不在框架范畴之内

已经做了消息离线，但是客户端自己断网，服务端只有在检测到没有心跳才会感知断开，导致查询离线消息不准确，消息丢失。看样子就还需要通过消息回执的方式来实现

**Comment by liangdas** [comment]
对做消息回执
