### ISSUE TITLE
rpc数据传输

### ISSUE THREAD

**Issue by shen3335600** [liangdas/mqant#97]
rpc直接的数据格式为什么没有切片类呢 比如 []map[string][string]或 []map[string]interface{}
marshal自定义可以增加一些使用例子吗，现在都是最简单的string，稍微复杂的格式无从下手

**Comment by liangdas** [comment]
复杂的数据结构可以用  protocolbuffer http://docs.mqant.com/protocolbuffer.html

**Comment by shen3335600** [comment]
注册了一个db服，该db服维护各种数据库连接池，并向其他服暴露统一增删改查接口
其他应用服只需要传入参数，db服可将查询结果返回，大部分返回的结果都是数据列表，所以切片可能更加合适
这样实现的话，需要非常灵活的数据结构作为返回解析，protobuf的数据结构严格，可能满足不了我这个需求
请问在golang中，mqant中有没有可以实现类似功能的思路呢，万分感谢

**Comment by liangdas** [comment]
没有呢
