### ISSUE TITLE
分布式部署

### ISSUE THREAD

**Issue by Yajun312890225** [liangdas/mqant#98]
看了分布式部署的文档，只有单机部署，mqant支持客户端连接服务器后，服务器将用户分配到不同的服务器，然后这些服务器连接同一个nats，如果支持，有没有具体的文档？还想问一下，如果服务启动时，服务发现consul还未启动，然后consul再启动，服务是没办法再重新注册服务发现的，是我哪里配置不对导致的吗？

**Comment by liangdas** [comment]
必须先保证consul可用再启动服务哈，分布式下各个进程都链接的同一个nats，所以多个进程就可以相互通信。
分布式部署跟单机部署没有区别，你可以简单的启动多个进程尝试模块间通信试试。

**Comment by Yajun312890225** [comment]
我已经通过那个分组的概念尝试过，已经可以。但如果进程是在两台机器上，不光需要连接到同一个nats，还需要连接到同一个consul，通过ProcessID进行区分，我发现当多个进程注册了同一个模块后，nats的分发好像是随机的（这个没问题），目前的方案是一个主服务注册所有模块，暴露一个接口对外，其他服务不注册Gate服，这样子是否有问题？我发现项目中存在appdash，这个是否集成或者说之后会不会集成进来？

**Comment by liangdas** [comment]
consul是注册中心，整个集群都得用相同的，多个模块注册后你的通过服务选择去调控访问哪个节点，否则就是随机的，这是微服务的基本操作http://docs.mqant.com/selector.html
